// Simulation-grade physics engine for mechatronics
export interface Vector3D {
  x: number;
  y: number;
  z: number;
}

export interface RigidBody {
  mass: number; // kg
  position: Vector3D;
  velocity: Vector3D;
  acceleration: Vector3D;
  rotation: Vector3D; // euler angles in radians
  angularVelocity: Vector3D; // rad/s
  angularAcceleration: Vector3D; // rad/s²
  inertia: Vector3D; // moment of inertia kg⋅m²
}

export interface Force {
  vector: Vector3D;
  point: Vector3D; // application point
}

export interface Motor {
  id: string;
  type: 'brushed' | 'brushless';
  // Mechanical properties
  maxTorque: number; // N⋅m
  maxRPM: number;
  currentRPM: number;
  targetRPM: number;
  // Electrical properties
  voltage: number; // V (supply voltage)
  current: number; // A (current draw)
  resistance: number; // Ω (armature/winding resistance)
  inductance: number; // H (for brushless motors)
  backEMFConstant: number; // Kv rating (RPM/V) or Ke (V/rad/s)
  torqueConstant: number; // Kt (N⋅m/A)
  // Performance
  efficiency: number; // 0-1
  power: number; // W
  temperature: number; // °C
  maxCurrent: number; // A (stall current)
  noLoadCurrent: number; // A
}

export interface Battery {
  capacity: number; // mAh
  nominalVoltage: number; // V (nominal cell voltage)
  cellCount: number; // number of cells in series
  currentCharge: number; // mAh
  internalResistance: number; // Ω
  dischargeCurrent: number; // A
  cRating: number; // discharge rate (e.g., 25C)
  // Voltage characteristics
  maxVoltage: number; // V (fully charged)
  minVoltage: number; // V (cutoff voltage)
  currentVoltage: number; // V (actual voltage under load)
  // State tracking
  stateOfCharge: number; // 0-1 (percentage)
  cycleCount: number;
  temperature: number; // °C
}

export interface Propeller {
  diameter: number; // inches
  pitch: number; // inches
  thrustCoefficient: number;
  powerCoefficient: number;
  rpm: number;
}

// Physical constants
export const GRAVITY = 9.81; // m/s²
export const AIR_DENSITY = 1.225; // kg/m³ at sea level
export const WATER_DENSITY = 1000; // kg/m³

// Vector operations
export const vecAdd = (a: Vector3D, b: Vector3D): Vector3D => ({
  x: a.x + b.x,
  y: a.y + b.y,
  z: a.z + b.z,
});

export const vecSub = (a: Vector3D, b: Vector3D): Vector3D => ({
  x: a.x - b.x,
  y: a.y - b.y,
  z: a.z - b.z,
});

export const vecScale = (v: Vector3D, s: number): Vector3D => ({
  x: v.x * s,
  y: v.y * s,
  z: v.z * s,
});

export const vecMag = (v: Vector3D): number => 
  Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z);

export const vecNorm = (v: Vector3D): Vector3D => {
  const mag = vecMag(v);
  return mag > 0 ? vecScale(v, 1 / mag) : { x: 0, y: 0, z: 0 };
};

export const vecDot = (a: Vector3D, b: Vector3D): number =>
  a.x * b.x + a.y * b.y + a.z * b.z;

export const vecCross = (a: Vector3D, b: Vector3D): Vector3D => ({
  x: a.y * b.z - a.z * b.y,
  y: a.z * b.x - a.x * b.z,
  z: a.x * b.y - a.y * b.x,
});

// ESC (Electronic Speed Controller) interface
export interface ESC {
  id: string;
  maxCurrent: number; // A
  voltage: number; // V
  pwmFrequency: number; // Hz
  throttleInput: number; // 0-1 (from receiver/controller)
  outputPower: number; // 0-1 (to motor)
  responseTime: number; // seconds (delay/ramping)
  efficiency: number; // 0-1
  brakingEnabled: boolean;
  currentThrottle: number; // internal state for ramping
  temperature: number; // °C
}

// Enhanced Motor Physics with Electrical Integration

// Calculate back-EMF voltage (voltage generated by motor rotation)
export const calculateBackEMF = (motor: Motor): number => {
  // Back-EMF: Vb = Ke * ω (where ω is angular velocity in rad/s)
  const omega = (motor.currentRPM * 2 * Math.PI) / 60;
  return motor.backEMFConstant * omega;
};

// Calculate motor current based on electrical model
export const calculateMotorCurrent = (motor: Motor, appliedVoltage: number): number => {
  // Motor electrical equation: V = I*R + Ke*ω
  // Therefore: I = (V - Ke*ω) / R
  const backEMF = calculateBackEMF(motor);
  const current = Math.max(motor.noLoadCurrent, (appliedVoltage - backEMF) / motor.resistance);
  return Math.min(current, motor.maxCurrent); // Limit to max current
};

// Calculate motor torque from current (more accurate than throttle-based)
export const calculateMotorTorque = (motor: Motor): number => {
  // Torque: T = Kt * I (torque constant * current)
  const torque = motor.torqueConstant * motor.current;
  
  // Apply efficiency losses
  const efficientTorque = torque * motor.efficiency;
  
  // Limit to max torque
  return Math.min(efficientTorque, motor.maxTorque);
};

// Calculate motor power
export const calculateMotorPower = (motor: Motor): number => {
  // P = V * I (electrical power) * efficiency
  return motor.voltage * motor.current * motor.efficiency;
};

// Update motor state with realistic dynamics
export const updateMotorState = (
  motor: Motor,
  targetVoltage: number,
  load: number,
  deltaTime: number
): Motor => {
  // Calculate current based on applied voltage
  const current = calculateMotorCurrent(motor, targetVoltage);
  
  // Calculate torque
  const motorTorque = calculateMotorTorque({ ...motor, current });
  
  // Net torque = motor torque - load torque
  const netTorque = motorTorque - load;
  
  // Angular acceleration: α = T / I (where I is moment of inertia)
  const momentOfInertia = 0.0001; // kg⋅m² (small for motors)
  const angularAcceleration = netTorque / momentOfInertia;
  
  // Update RPM: ω = ω0 + α*dt (convert rad/s² to RPM)
  const rpmChange = (angularAcceleration * 60) / (2 * Math.PI) * deltaTime;
  const newRPM = Math.max(0, Math.min(motor.maxRPM, motor.currentRPM + rpmChange));
  
  // Calculate temperature rise (simplified)
  const heatGenerated = current * current * motor.resistance;
  const cooling = (motor.temperature - 25) * 0.1; // Simple cooling
  const tempChange = (heatGenerated - cooling) * deltaTime;
  
  return {
    ...motor,
    currentRPM: newRPM,
    voltage: targetVoltage,
    current,
    power: calculateMotorPower({ ...motor, current, voltage: targetVoltage }),
    temperature: motor.temperature + tempChange,
  };
};

// ESC Functions - Convert PWM signal to motor voltage with realistic response

export const updateESCOutput = (esc: ESC, throttleInput: number, deltaTime: number): ESC => {
  // ESC response time creates lag (exponential smoothing)
  const rampRate = 1 / esc.responseTime; // how fast ESC responds
  const targetThrottle = Math.max(0, Math.min(1, throttleInput));
  
  // Exponential smoothing for realistic ramping
  const alpha = Math.min(1, rampRate * deltaTime);
  const newThrottle = esc.currentThrottle + alpha * (targetThrottle - esc.currentThrottle);
  
  // Convert throttle to output power (may include calibration curve)
  const outputPower = newThrottle * esc.efficiency;
  
  // Calculate heat from inefficiency
  const powerLoss = (1 - esc.efficiency) * newThrottle * esc.voltage * esc.maxCurrent;
  const tempChange = powerLoss * deltaTime * 0.01;
  
  return {
    ...esc,
    throttleInput,
    currentThrottle: newThrottle,
    outputPower,
    temperature: esc.temperature + tempChange,
  };
};

// Propeller physics
export const calculatePropellerThrust = (prop: Propeller): number => {
  // Thrust = C_T * ρ * n² * D⁴
  // where n = RPS (revolutions per second), D = diameter in meters
  const rps = prop.rpm / 60;
  const diameter = prop.diameter * 0.0254; // inches to meters
  return prop.thrustCoefficient * AIR_DENSITY * Math.pow(rps, 2) * Math.pow(diameter, 4);
};

export const calculatePropellerPower = (prop: Propeller): number => {
  // Power = C_P * ρ * n³ * D⁵
  const rps = prop.rpm / 60;
  const diameter = prop.diameter * 0.0254;
  return prop.powerCoefficient * AIR_DENSITY * Math.pow(rps, 3) * Math.pow(diameter, 5);
};

// Drag forces
export const calculateDrag = (velocity: Vector3D, dragCoefficient: number, area: number): Vector3D => {
  // F_d = 0.5 * ρ * v² * C_d * A
  const speed = vecMag(velocity);
  if (speed === 0) return { x: 0, y: 0, z: 0 };
  
  const dragMag = 0.5 * AIR_DENSITY * speed * speed * dragCoefficient * area;
  const direction = vecNorm(velocity);
  return vecScale(direction, -dragMag); // opposite to velocity
};

// Lift forces (for wings/airfoils)
export const calculateLift = (velocity: Vector3D, liftCoefficient: number, area: number, upVector: Vector3D): Vector3D => {
  // F_l = 0.5 * ρ * v² * C_l * A
  const speed = vecMag(velocity);
  if (speed === 0) return { x: 0, y: 0, z: 0 };
  
  const liftMag = 0.5 * AIR_DENSITY * speed * speed * liftCoefficient * area;
  return vecScale(upVector, liftMag);
};

// Friction forces
export const calculateFriction = (normal: number, velocity: Vector3D, frictionCoeff: number): Vector3D => {
  // F_f = μ * N * direction
  const speed = vecMag(velocity);
  if (speed === 0) return { x: 0, y: 0, z: 0 };
  
  const frictionMag = frictionCoeff * normal;
  const direction = vecNorm(velocity);
  return vecScale(direction, -frictionMag);
};

// Advanced Battery Discharge Model

// Calculate battery voltage based on state of charge (realistic discharge curve)
export const calculateBatteryVoltage = (battery: Battery): number => {
  const soc = battery.stateOfCharge;
  const cellVoltage = battery.nominalVoltage;
  
  // Realistic LiPo discharge curve (per cell)
  // Voltage varies non-linearly with SOC
  let perCellVoltage: number;
  if (soc > 0.9) {
    // Fully charged: 4.2V
    perCellVoltage = 4.2 - (1 - soc) * 2;
  } else if (soc > 0.2) {
    // Normal range: 4.0V to 3.7V (roughly linear)
    perCellVoltage = 3.7 + (soc - 0.2) * 0.3 / 0.7;
  } else if (soc > 0.05) {
    // Low battery: 3.7V to 3.4V (rapid drop)
    perCellVoltage = 3.4 + (soc - 0.05) * 0.3 / 0.15;
  } else {
    // Critical: below 3.4V
    perCellVoltage = 3.0 + soc * 0.4 / 0.05;
  }
  
  // Total voltage = cell voltage * cell count
  const openCircuitVoltage = perCellVoltage * battery.cellCount;
  
  // Voltage drop under load: V = V_oc - I*R
  const voltageDrop = battery.dischargeCurrent * battery.internalResistance;
  
  return Math.max(battery.minVoltage, openCircuitVoltage - voltageDrop);
};

// Check if battery can supply the requested current
export const canBatterySupplyCurrent = (battery: Battery, requestedCurrent: number): boolean => {
  const maxDischargeCurrent = (battery.capacity / 1000) * battery.cRating;
  return requestedCurrent <= maxDischargeCurrent && battery.stateOfCharge > 0.05;
};

// Update battery state with realistic discharge characteristics
export const updateBattery = (battery: Battery, current: number, deltaTime: number): Battery => {
  // Check if current exceeds max discharge rate
  const maxCurrent = (battery.capacity / 1000) * battery.cRating;
  const actualCurrent = Math.min(current, maxCurrent);
  
  // Capacity used: Q = I * t (convert to mAh)
  const chargeUsed = (actualCurrent * deltaTime * 1000) / 3600; // mAh
  const newCharge = Math.max(0, battery.currentCharge - chargeUsed);
  
  // Update state of charge
  const newSOC = newCharge / battery.capacity;
  
  // Calculate current voltage
  const tempBattery = {
    ...battery,
    currentCharge: newCharge,
    stateOfCharge: newSOC,
    dischargeCurrent: actualCurrent,
  };
  const voltage = calculateBatteryVoltage(tempBattery);
  
  // Temperature rise from internal resistance (simplified)
  const heatGenerated = actualCurrent * actualCurrent * battery.internalResistance;
  const cooling = (battery.temperature - 25) * 0.05; // ambient cooling
  const tempChange = (heatGenerated - cooling) * deltaTime * 0.1;
  
  // Internal resistance increases slightly as battery drains
  const resistanceMultiplier = 1 + (1 - newSOC) * 0.2;
  
  return {
    ...battery,
    currentCharge: newCharge,
    stateOfCharge: newSOC,
    currentVoltage: voltage,
    dischargeCurrent: actualCurrent,
    temperature: battery.temperature + tempChange,
    internalResistance: battery.internalResistance * resistanceMultiplier,
  };
};

// Gear ratio calculations
export const applyGearRatio = (inputTorque: number, inputRPM: number, gearRatio: number) => {
  // Output torque = Input torque * gear ratio
  // Output RPM = Input RPM / gear ratio
  return {
    outputTorque: inputTorque * gearRatio,
    outputRPM: inputRPM / gearRatio,
  };
};

// Rigid body dynamics integration (Euler method)
export const updateRigidBody = (body: RigidBody, forces: Force[], deltaTime: number): RigidBody => {
  // Sum all forces
  let netForce: Vector3D = { x: 0, y: 0, z: 0 };
  let netTorque: Vector3D = { x: 0, y: 0, z: 0 };
  
  forces.forEach(force => {
    netForce = vecAdd(netForce, force.vector);
    // Torque = r × F (cross product of position and force)
    const torque = vecCross(force.point, force.vector);
    netTorque = vecAdd(netTorque, torque);
  });
  
  // F = ma -> a = F/m
  const acceleration = vecScale(netForce, 1 / body.mass);
  
  // τ = Iα -> α = τ/I
  const angularAcceleration: Vector3D = {
    x: body.inertia.x > 0 ? netTorque.x / body.inertia.x : 0,
    y: body.inertia.y > 0 ? netTorque.y / body.inertia.y : 0,
    z: body.inertia.z > 0 ? netTorque.z / body.inertia.z : 0,
  };
  
  // Update velocity: v = v0 + a*dt
  const velocity = vecAdd(body.velocity, vecScale(acceleration, deltaTime));
  
  // Update position: x = x0 + v*dt
  const position = vecAdd(body.position, vecScale(velocity, deltaTime));
  
  // Update angular velocity: ω = ω0 + α*dt
  const angularVelocity = vecAdd(body.angularVelocity, vecScale(angularAcceleration, deltaTime));
  
  // Update rotation: θ = θ0 + ω*dt
  const rotation = vecAdd(body.rotation, vecScale(angularVelocity, deltaTime));
  
  return {
    ...body,
    position,
    velocity,
    acceleration,
    rotation,
    angularVelocity,
    angularAcceleration,
  };
};

// Collision detection (simple bounding sphere)
export const checkCollision = (pos1: Vector3D, radius1: number, pos2: Vector3D, radius2: number): boolean => {
  const distance = vecMag(vecSub(pos1, pos2));
  return distance < (radius1 + radius2);
};

// Collision response with elasticity
export const resolveCollision = (
  body1: RigidBody,
  body2: RigidBody,
  elasticity: number = 0.8
): { body1: RigidBody; body2: RigidBody } => {
  const normal = vecNorm(vecSub(body2.position, body1.position));
  const relativeVelocity = vecSub(body1.velocity, body2.velocity);
  const velocityAlongNormal = vecDot(relativeVelocity, normal);

  if (velocityAlongNormal > 0) return { body1, body2 };

  const impulse = -(1 + elasticity) * velocityAlongNormal / (1 / body1.mass + 1 / body2.mass);

  const impulseVector = vecScale(normal, impulse);
  
  return {
    body1: {
      ...body1,
      velocity: vecAdd(body1.velocity, vecScale(impulseVector, 1 / body1.mass)),
    },
    body2: {
      ...body2,
      velocity: vecSub(body2.velocity, vecScale(impulseVector, 1 / body2.mass)),
    },
  };
};

// Ground collision
export const checkGroundCollision = (position: Vector3D, groundLevel: number = 0): boolean => {
  return position.y <= groundLevel;
};

export const resolveGroundCollision = (body: RigidBody, elasticity: number = 0.5): RigidBody => {
  if (body.position.y < 0) {
    return {
      ...body,
      position: { ...body.position, y: 0 },
      velocity: { ...body.velocity, y: -body.velocity.y * elasticity },
    };
  }
  return body;
};

// Fluid dynamics for boats
export const calculateBuoyancy = (
  submergedVolume: number,
  fluidDensity: number = WATER_DENSITY
): Vector3D => {
  // F_b = ρ * V * g
  const buoyancyForce = fluidDensity * submergedVolume * GRAVITY;
  return { x: 0, y: buoyancyForce, z: 0 };
};

export const calculateWaterDrag = (velocity: Vector3D, dragCoefficient: number = 1.5): Vector3D => {
  // Water drag is similar to air drag but with water density
  const speed = vecMag(velocity);
  if (speed === 0) return { x: 0, y: 0, z: 0 };
  
  const dragMag = 0.5 * WATER_DENSITY * speed * speed * dragCoefficient * 0.1; // area
  const direction = vecNorm(velocity);
  return vecScale(direction, -dragMag);
};

export const calculateWaveForce = (position: Vector3D, time: number, amplitude: number = 0.3): Vector3D => {
  // Simple sinusoidal wave
  const waveHeight = amplitude * Math.sin(position.x * 0.5 + time * 2);
  const waveForce = waveHeight * 10; // Force based on wave
  return { x: 0, y: waveForce, z: 0 };
};

// Simple PID controller for stability
export interface PIDController {
  kp: number; // proportional gain
  ki: number; // integral gain
  kd: number; // derivative gain
  integral: number;
  previousError: number;
}

export const updatePID = (pid: PIDController, error: number, deltaTime: number): { output: number; pid: PIDController } => {
  const integral = pid.integral + error * deltaTime;
  const derivative = (error - pid.previousError) / deltaTime;
  
  const output = pid.kp * error + pid.ki * integral + pid.kd * derivative;
  
  return {
    output,
    pid: {
      ...pid,
      integral,
      previousError: error,
    },
  };
};
